[workspace]
resolver = "2"
members = [
    "crates/da-core",
    "crates/da-graph",
    "crates/da-thermal",
    "crates/da-param",
    "crates/da-sim",
    "crates/da-econ",
    "crates/da-audio",
    "crates/da-render",
    "apps/darkair",
    "apps/da-edit",
    "tools/osgedit",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
glam = { version = "0.29", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
ron = "0.8"
serde_json = "1"
rayon = "1.10"

wgpu = "23"
pollster = "0.4"
bytemuck = { version = "1", features = ["derive"] }
winit = "0.30"
image = { version = "0.24", default-features = false, features = ["png"] }
eframe = { version = "0.30", default-features = false, features = ["wgpu", "default_fonts", "wayland", "x11", "persistence"] }
egui = "0.30"
egui-wgpu = "0.30"

da-core = { path = "crates/da-core" }
da-render = { path = "crates/da-render" }
da-graph = { path = "crates/da-graph" }
da-thermal = { path = "crates/da-thermal" }
da-param = { path = "crates/da-param" }
da-sim = { path = "crates/da-sim" }
da-econ = { path = "crates/da-econ" }
da-audio = { path = "crates/da-audio" }

kira = { version = "0.10", default-features = false, features = ["cpal"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
