[package]
name = "da-edit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
da-core = { workspace = true }
da-graph = { workspace = true }
da-thermal = { workspace = true }
da-param = { workspace = true }
da-render = { workspace = true }
glam = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
wgpu = { workspace = true }
